name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install sphinx sphinx-breeze-theme breathe sphinx_copybutton

      - name: Check for Broken Links
        run: |
          sphinx-build -b linkcheck docs/source docs/build/linkcheck

      - name: Build HTML Documentation
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Deploy to GitHub Pages Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
